apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  externalName: {{PG_RDS_ENDPOINT_ADDRESS}}
  selector:
    component: postgres
  type: ExternalName
  ports:
    - port: 5432
      targetPort: 5432
status:
  loadBalancer: {}
