apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  externalName: {{REDIS_ENDPOINT_ADDRESS}}
  selector:
    component: redis
  type: ExternalName
  ports:
    - port: 6379
      targetPort: 6379